### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by pxl-th** [ROCmSoftwarePlatform/rocSPARSE#347]
Official documentation for [rocSPARSE](https://rocm.docs.amd.com/projects/rocSPARSE/en/latest/usermanual.html#rocsparse-csc2dense) is broken for a lot of functions.

One such example:
![image](https://github.com/ROCmSoftwarePlatform/rocSPARSE/assets/17990405/e2c24d4f-a901-4501-909c-837e7d1be053)

**Comment by cgmb** [comment]
@saadrahim @samjwu

We lost the checks for this when we dropped the docs builds from the math-ci static analysis job. When we moved to using RTD builds, I opposed enabling warnings-as-errors in our ReadTheDocs configurations because (1) we had the math-ci building the docs with warnings-as-errors anyway, and (2) I was concerned we'd have no way to fix problems if a tag failed to build on ReadTheDocs.

Neither (1) nor (2) are relevant anymore. We have removed the math-ci docs build because it is redundant and we now build our official documentation from the docs-<version> branch rather than directly from the release tag.

There's currently a task to enable doxygen warnings-as-errors in all our libraries libraries, but we should also enable sphinx warnings-as-errors in our `.readthedocs.yaml`.

**Comment by cgmb** [comment]
Thanks @pxl-th for bringing this to our attention.

**Comment by samjwu** [comment]
Thanks for pointing this out. Fixed now: https://rocm.docs.amd.com/projects/rocSPARSE/en/latest/usermanual.html#types

There was an error in the Doxyfile INPUT config for the versioned docs branches. I've backported the fix for 5.0.0 docs to 5.6.0 docs. The develop branch already had the fix so future releases won't have this issue.

**Comment by samjwu** [comment]
Added Sphinx as warning config to the doc standardization issue/task
